### ISSUE TITLE
Should we link to German resources from English pages?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-TellMeSomethingAbout#8]
I think it would be better to only link to English resources from the English pages. A German branch could be created to link to the German resources. It makes it easier for people just glancing over the page to find things.

It has been criticized again and again that there is still too much information in German (just recently during a session at t3cmd 2019), that it is difficult to find information in English. I think, adding German links to official English texts sends the wrong signal, that might give the impression that TYPO3 is a German product and unaccessible for people not speaking German.

**Comment by kaystrobach** [comment]
Maybe we nees no english / german branches but sections?

**Comment by sypets** [comment]
Sorry, I meant using other language in subdirectory, e.g. Localization.de-DE  that makes language selectable via version selector, not branch. 

But any clear separation of English and German would be ok, I think.

**Comment by sypets** [comment]
Related: There is effort by some people (including TYPO3 content group and TYPO3 association, but from various members of the community as well) to make more information available in English (instead of only in German) and make it easier for non-German speaking people to use TYPO3, see also [thread on Twitter](https://twitter.com/Haassie82/status/1104392904762634240).

Some German bloggers have even switched to English for their blogs.

Still, **not finding information in English or only in German** is still mentioned by non-German speakers as something that makes it difficult for them to use TYPO3 (e.g. TYPO3 book session at t3cmd19). 

Meanwhile, I would be in favor of removing the links to German resources entirely from "Tell me Something About X". I don't want to make it more difficult for non-English speaking Germans but _if_ there needs to be a choice between making it easier for non-German speaking or non-English speaking, I would be in favor of the English speaking community, at least on docs.typo3.org.

**Comment by kaystrobach** [comment]
mhmm how about having several language sections in that "tell me something about" section?

* first has to be english, there needs to be atleast one english article, covering most of the topic
* following with articles in other languages, which are marked with the language the article has

**Comment by DanielSiepmann** [comment]
Like the idea of @kaystrobach, https://www.typo3book.com/resources is doing the same. This way everyone doing English is encouraged, while foreign languages are still respected.
